on:
  pull_request:
  workflow_dispatch:
  push: { branches: main}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker-compose up
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: docker-compose up -d
    - name: Check running containers
      run: docker-compose ps -a
    - name: Check logs
      run: docker-compose logs tightlock-api
    - name: dags unit tests  
      run: docker-compose exec airflow-worker pytest -v --mypy --cov

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Integration Tests
        run: | 
          chmod +x ./run_integration_tests.sh
          bash ./run_integration_tests.sh