on:
  pull_request:
  workflow_dispatch:
  push: { branches: master }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-compose up
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: docker-compose up -d
    - name: Check running containers
      run: docker-compose ps -a
    - name: Check logs
      run: docker-compose logs tightlock-api
    - name: Test with pytest
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: docker exec tightlock-api pytest
